test:
  outputs:
    dev:
      catalog: test-dev
      host: dbc-9bf38070-d55e.cloud.databricks.com
      http_path: /sql/1.0/warehouses/e34022bc09111f0f
      schema: default
      threads: 1
      type: databricks
      # Use an environment variable securely passed into the Docker container
      token: "{{ env_var('DBT_DATABRICKS_TOKEN') }}" 
  target: dev